### ISSUE TITLE
Oauth error

### ISSUE THREAD

**Issue by cyberbudy** [viagogo/gogokit.py#4]
When I'm trying to get access token like this

`client.oauth.get_client_access_token()`

I receive an error:

`
{'status_code': 400, 'reason': 'Bad Request', 'error': {'error': 'unsupported_grant_type'}}
`

I suppose problem in HttpClient where post submits data in json, but viagogo requires application/x-www-form-urlencoded content-type

**Comment by maxab** [comment]
Hi @cyberbudy, Can you clarify how did you get the credentials of the api?

**Comment by cyberbudy** [comment]
A friend of mine gave his to me.
Does it matter?

**Comment by maxab** [comment]
It does because the error is saying that the keys don't have access to the api ('unsupported_grant_type')

**Comment by cyberbudy** [comment]
Hmm, but when I send data manually like
`requests.post(data=data, headers=headers...)`
everything works fine

**Comment by maxab** [comment]
You were right, this will be fixed in the next release.

**Comment by craigbarrett** [comment]
@maxab how does a client get API access?
